steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: install
      workingDir: "$(Build.SourcesDirectory)/Components"
  - task: Npm@1
    displayName: "Build Angular"
    inputs:
      command: custom
      customCommand: run build
      workingDir: "$(Build.SourcesDirectory)/Components"
  - task: CopyFiles@2
    displayName: "copy Components to artifact staging directory"
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/Components/dist"
      contents: "**"
      targetFolder: "$(Build.ArtifactStagingDirectory)/Components"
  - task: CopyFiles@2
    displayName: "copy infrastructure to artifact staging directory"
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/Infrastructure"
      contents: "**"
      targetFolder: "$(Build.ArtifactStagingDirectory)/Infrastructure"
  - task: PublishPipelineArtifact@1
    displayName: "publish artifact"
    inputs:
      artifactName: drop
      targetPath: $(Build.ArtifactStagingDirectory)
