steps:
  - task: Npm@1
    displayName: "npm install"
    inputs:
      command: install
      workingDir: "$(Build.SourcesDirectory)/components"
  - task: Npm@1
    displayName: "Build Angular"
    inputs:
      command: custom
      customCommand: run build
      workingDir: "$(Build.SourcesDirectory)/components"
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "drop"
      targetPath: "$(Build.SourcesDirectory)/components/dist"
